# Generated by Django 3.1b1 on 2020-08-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjcl_app', '0007_searches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searches',
        ),
    ]
