# Generated by Django 3.1b1 on 2020-08-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjcl_app', '0011_searchers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchers',
        ),
    ]
